# Generated by Django 3.0.5 on 2020-05-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import re7.authentication.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('1', 'Simple'), ('2', 'Modéré'), ('3', 'Difficile')], max_length=1)),
                ('prep_time', models.PositiveSmallIntegerField()),
                ('bake_time', models.PositiveSmallIntegerField()),
                ('total_time', models.PositiveSmallIntegerField()),
                ('photo', models.ImageField(default='recipe-default-image.jpg', upload_to='photos')),
                ('creater', models.ForeignKey(default=re7.authentication.models.deleted_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipes', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('L', 'L'), ('cL', 'cL')], max_length=5)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.Recipe')),
            ],
        ),
    ]
