# Generated by Django 3.0.5 on 2020-04-21 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[(1, 'Simple'), (2, 'Modéré'), (3, 'Difficile')], max_length=10)),
                ('prep_time', models.PositiveSmallIntegerField()),
                ('bake_time', models.PositiveSmallIntegerField()),
                ('total_time', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
