# Generated by Django 3.0.5 on 2020-05-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nb_covers',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
