# Generated by Django 3.0.5 on 2020-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default='recipe-default-image.jpg', upload_to='photos'),
        ),
    ]
